{
 "title": "Custom Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Last Hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order Status Last Hour",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(status) (increase(orders_status_total{status=~\"PENDING_PAYMENT|CANCELLED\"}[10m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Cancel Calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{uri=\"/orders/{orderId}/cancel\"}[5m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders Created Last Hour",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(orders_status_total{status=\"CREATED\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores orquestador",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    sum(increase(http_server_requests_seconds_count{status=~\"5..\", application=\"order-orchestrator-service-v1\"}[5m]))\n    /\n    sum(increase(http_server_requests_seconds_count{application=\"order-orchestrator-service-v1\"}[5m]))\n  ) * 100, 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Errors per Minute",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Incomes Last Hour",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(transaction_amount_sum[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}