spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JeanDev2X/microservicios.git
          search-paths: infra/config-server-properties
          clone-on-start: true
          default-label: main
          username: JeanDev2X
          #Para generar el token ir a https://github.com/settings/tokens
          password: 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
          force-pull: true